from . import mgmtsystem_security_control
from . import iso27001_gap
from . import iso27001_gap_line
from . import iso27001_soa
from . import iso27001_soa_line
from . import iso27001_clause
from . import iso27001_policy
from . import mgmtsystem_action
from . import mgmtsystem_audit
from . import res_config
